### ISSUE TITLE
[CommandsEx] Error

### ISSUE THREAD

**Issue by ItzAtomikHD** [TPAPlayer/help#1]
![daerror](https://cloud.githubusercontent.com/assets/22156828/19006092/d389a8da-8755-11e6-8a0c-be74edb49890.PNG)

I don't even understand why this was released. It does not even support 1.10. Did you even test this?
SOLVED

**Comment by GreninjaPro321** [comment]
Hold on for a second, i thought its supported 1.10.

**Comment by GreninjaPro321** [comment]
and umm... try it out and see what happens...

**Comment by GreninjaPro321** [comment]
I will go and test it out... okay?

**Comment by GreninjaPro321** [comment]
I test the server and the plugin is green. I do /tp and it didnt work, thanks for a support btw we will fix it.

**Comment by GreninjaPro321** [comment]
This plugin is not supported in 1.10, its only supported in 1.5.2
@ItzAtomikHD

**Comment by GreninjaPro321** [comment]
I have close this down people because it is solved...
